dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - npm install

before_script:
  - yarn global add @angular/cli

script:
  - ng test --single-run --no-progress --browser=ChromeHeadlessCI
  - npm run e2e -- --no-progress --config=protractor-ci.conf.js
