dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - npm install

before_script:
  - yarn global add @angular/cli

jobs:
  include:
    - stage: "unit tests"
      script: npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI
    - stage: "e2e tests"
      script: npm run start
    - script: npm run webdriver-update
    - script: npm run e2e -- protractor-ci.conf.js
